WebApinMVC/WebApinMVC/MVCParentApplication/Controllers/userMVCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCParentApplication.Models;
using System.Net.Http;

namespace MVCParentApplication.Controllers
{
    public class userMVCController : Controller
    {
        // GET: userMVC
        public ActionResult Index()
        {
            IEnumerable<MVCuserModel> userlist;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("usercontactdetails").Result;
            userlist = response.Content.ReadAsAsync<IEnumerable<MVCuserModel>>().Result;
            return View(userlist);
        }

        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new MVCuserModel());
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("UserContactDetails/" + id.ToString()).Result;
                return View(response.Content.ReadAsAsync<MVCuserModel>().Result);
            }
        }
        [HttpPost]
        public ActionResult AddOrEdit(MVCuserModel user)
        {
            if (user.UserContactDetailUID == 0)
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("UserContactDetails", user).Result;
                TempData["SuccessMessage"] = "Saved Successfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("UserContactDetails/" + user.UserContactDetailUID, user).Result;
                TempData["SuccessMessage"] = "Updated Successfully";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.WebApiClient.DeleteAsync("UserContactDetails/" + id.ToString()).Result;
            TempData["SuccessMessage"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

WebApinMVC/WebApinMVC/MVCParentApplication/Views/userMVC/AddOrEdit.cshtml
@model MVCParentApplication.Models.MVCuserModel
@{
    ViewBag.Title = "AddOrEdit";
}

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.UserContactDetailUID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName)
            @Html.EditorFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber)
            @Html.EditorFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email)
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Inactive)
            @Html.EditorFor(model => model.Inactive)
            @Html.ValidationMessageFor(model => model.Inactive)
        </div>

        <div class="form-group">
            <input type="submit" value="Submit" class="btn button" />
            <input type="reset" value="Reset" class="btn button" />
        </div>
    }
</div>


@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
}

WebApinMVC/WebApinMVC/MVCParentApplication/Views/userMVC/Index.cshtml
@model IEnumerable<MVCParentApplication.Models.MVCuserModel>

@{
    ViewBag.Title = "Index";
}

<br />
<p>
    <a href="@Url.Action("AddOrEdit","userMVC")" class="btn btn-default"><i class="fa fa-plus"></i> Create New</a>
</p>
<table class="table table-striped">
    <thead class="table-heading">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserContactDetailUID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inactive)
            </th>
            <th>Actions</th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserContactDetailUID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inactive)
            </td>
            <td>
                <a href="@Url.Action("AddOrEdit", "userMVC", new { id = item.UserContactDetailUID })" class="btn btn-default"><i class="fa fa-pencil"></i>  Edit</a>
                <a onclick="Delete(@item.UserContactDetailUID)" class="btn btn-default"><i class="fa fa-trash"></i>  Delete</a>
            </td>
        </tr>
    }

</table>

@section scripts{
    <script>
        $(function () {
            var successMessage = '@TempData["SuccessMessage"]'
            if (successMessage != '')
                alertify.success(successMessage);
        });

        function Delete(id) {
            alertify.confirm('Web Api CRUD Operations','Are You Sure to Delete this Record ?',function(){
                window.location.href  = '@Url.Action("Delete", "userMVC")/'+id;
            },null );
        }
    </script>
}